version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_network

volumes:
  mysql_data:


networks:
  dev_network:
